version: '3.1'

services:
  mongo:
    image: mongo:5.0.9
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=core
    networks:
      - ddd
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - ddd
volumes:
  mongodb:
  mongoconfig:


networks:
  ddd:
    driver: bridge
